---
title: "Control Non-Coding Set"
author: "Patrick Short"
date: "6 May 2016"
output: html_document
---

We will compare the enhancer elements and the ultra-conserved elements to a set of control non-coding elements. The control elements were generated by subtracted the non-coding elements and the gencode v19 coding sequence from the probe set with at least 10x median coverage.

```{r check control set, echo = FALSE}
source("~/phd/code/MACB/R/mutation_null_model.R")

poisson_bar_ggplot <- function(p, obs, main, buffer =50){
  p = p[1:(obs+buffer+1)]
  counts = unlist(mapply(function(count, times) rep(count, times), seq(0, obs+buffer), round(1000000*p)))
  sim_hist(counts, obs, main = main)
}

de_novo_full = read.table("~/phd/code/CNE/data/de_novos.ddd_4k.noncoding_included.txt", header = TRUE, sep = "\t")
de_novo_full = subset(de_novo_full, pp_dnm > 0.00781)
control_elements = read.table("../data/control_noncoding.txt", header = TRUE, sep = "\t")
#control_elements = subset(control_elements, chr == "chr1")

control_dns = filter_with_bed(de_novo_full, control_elements)

control_elements$seq = as.character(getSeq(Hsapiens, control_elements$chr, control_elements$start, control_elements$stop))

control_elements$p_snp_null = 2 * sapply(control_elements$seq, p_sequence)

# full set
pop = 4294
lambda_control = dpois(x = seq(0, 400), sum(control_elements$p_snp_null)*pop)
obs_control = nrow(control_dns)

poisson_bar_ggplot(lambda_control, obs_control, main = "De Novo Mutations in Control Sequences")
```

Looking in the coding regions instead:

```{r coding regions, echo = FALSE}

cds_mut_rates = read.table("../data/coding_mutation_rates.gencode_v19_CDS.txt", header = TRUE, sep = "\t")
transcript_mut_rates = read.table("~/phd/code/CNE/data/de_novos.d", header = TRUE, sep = "\t")

cds = read.table("../data/gencode.v19.CDS.min_10_coverage.gene_union.txt", header = TRUE, sep = "\t")

de_novo_coding = filter_with_bed(de_novo_full, cds)
de_novo_coding_syn = subset(de_novo_coding, consequence == "synonymous_variant")

synonymous_rate = sum(cds_mut_rates$p_snp_synonymous) * 2

# full set
pop = 4294
p_dist_syn = dpois(x = seq(0, 2000), synonymous_rate*pop)

obs_syn = nrow(de_novo_coding_syn)

poisson_bar_ggplot(p_dist_syn, obs_syn, main = "De Novo Mutations in Synonymous Sites")

```
